### ISSUE TITLE
[Feature Request] Downloading thumbnails on first start: progress indicator + cancel button

### ISSUE THREAD

**Issue by AntonioNoack** [RareDevs/Rare#226]
**Is your feature request related to a problem? Please describe.**
When I launched Rare the first time, it downloaded images for a few minutes.
I have two issues with that:
a) Progress bar and download speed are missing
b) Cannot be skipped. Isn't Rare supposed to be lightweight? Why do I need those thumbnails then?

**Describe the solution you'd like**
I'd like a progress bar and a "cancel" button, so I can skip downloading these thumbnails.

**Describe alternatives you've considered**
-

**Additional context**
Windows 10, Personal Edition

**Comment by loathingKernel** [comment]
The images are downloaded once. On  the next start if they are found they won't downloaded again. That dialog is also for updating the games' metadata to discover new games or updates, so it can't be skipped.

a) The progressbar has been updated in the current development version of Rare from git to more accurately reflect the download progress, it will be included when the next version is released. Download speed is not something we will do because they are multiple very small downloads done in parallel and inferring the accumulated download speed is going to unnecessarily complicate the implementation.

b) Skip is not something we will add, the images are required for the UI to present itself properly and for the desktop shortcuts. If the thumbnails are considered "bloat" maybe using legendary from the command line is more fitting to your needs.

One of the current WIP features is to not require to download the images in the beginning but do it after Rare has loaded. This has not made it yet into the main development branch but we have tested it and it is in a working state. It will be included in some future version after the next one.

**Comment by SuperSamus** [comment]
Images are now downloaded after the initial loading.
(Though there is still no way to not download them at all)

**Comment by loathingKernel** [comment]
I believe this can be closed now. In recent versions the thumbnails are dynamically downloaded/loaded when the are required for the first time. Not downloading them at all might be included in the future, as it should be fairly easy now, but I find it hard to justify doing that.
