### ISSUE TITLE
[BUG] Mangohud Doesn't Work

### ISSUE THREAD

**Issue by LordofArcana** [RareDevs/Rare#482]
**Mangohud is not working**

Enabled mangohud from general settings, used global settings for the games and tested with 3 different games.

![resim](https://github.com/user-attachments/assets/f194e505-c634-4746-8534-4af1dded1bf6)

**Additional Info**

System: Debian Stable
Rare is installed with pipx. Mangohud is installed from repo. Works on terminal (mangohud glxgears or mangohud vkcube).
There are no errors about mangohud in logs.

**Comment by LordofArcana** [comment]
I installed current latest version (Garlic Crab) with pip from git. Still not working.
![resim](https://github.com/user-attachments/assets/df334c0b-95f9-4ae3-a869-2ce30b318532)
UPDATE: I manually installed dxvk to prefix i use rare on and now its working.

**Comment by loathingKernel** [comment]
>  UPDATE: I manually installed dxvk to prefix i use rare on and now its working.

That's probably the reason it didn't work before too. We do not use the `mangohud` wrapper, since most of the time games run using DXVK. We only set the `MANGOHUD=1` env variable to enable it. If you want to use `mangohud` with OpenGL, then you can provide the wrapper in the relevant field. 
![image](https://github.com/user-attachments/assets/577887a7-f122-44f3-9a8e-bf23a9404ae8)

**Comment by LordofArcana** [comment]
Old version was using this wrapper but it was not working with OpenGL. I also tried manually entering mangohud wrapper on old version and had the same result. Thanks for the help anyways.
